ARG DOCKERSRC=frommakefile
#
FROM ${DOCKERSRC}
#
ARG PUID=1001
ARG PGID=1001
ENV NPM_VERSION=latest \
    YARN_VERSION=latest
#
RUN addgroup -g ${PGID} -S alpine \
    && adduser -u ${PUID} -G alpine -h /home/alpine -D alpine
RUN set -xe \
    # echo "http://dl-cdn.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories && \
    && apk add -Uu --purge --no-cache curl git openssl nodejs nodejs-npm python \
    && if [ -n $(which npm) ]; then \
        echo "Installing npm@${NPM_VERSION}"; \
        npm install -g npm@${NPM_VERSION} yarn@${YARN_VERSION} \
	    && npm ls \
        && find /usr/lib/node_modules/npm -name test -o -name .bin -type d | xargs rm -rf; \
    fi \
    && rm -rf /usr/share/man /tmp/* /var/cache/apk/* /root/.npm /root/.node-gyp \
        /usr/lib/node_modules/npm/man /usr/lib/node_modules/npm/doc /usr/lib/node_modules/npm/html
# ENTRYPOINT ["/init"]
# ENTRYPOINT ["/usr/bin/node"]
