ARG ARCH=frommakefile
ARG DOCKERSRC=frommakefile
ARG USERNAME=frommakefile
#
FROM ${USERNAME}/${DOCKERSRC}:${ARCH}
#
ARG PUID=1001
ARG PGID=1001
ENV ARCH=linux-armv7l NPM_VERSION=latest
#
RUN addgroup -g ${PGID} -S alpine && \
    adduser -u ${PUID} -G alpine -h /home/alpine -D alpine
RUN set -xe && \
    # echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories && \
    apk add -Uu --purge --no-cache curl python openssl nodejs nodejs-npm && \
      if [ -n $(which npm) ]; then \
#        echo "Installing npm@${NPM_VERSION}"; \
#        npm install -g npm@${NPM_VERSION} --loglevel=debug && \
	npm ls && \
        find /usr/lib/node_modules/npm -name test -o -name .bin -type d | xargs rm -rf; \
      fi && \
      rm -rf /usr/share/man /tmp/* /var/cache/apk/* /root/.npm /root/.node-gyp \
    /usr/lib/node_modules/npm/man /usr/lib/node_modules/npm/doc /usr/lib/node_modules/npm/html
# ENTRYPOINT ["/init"]
# ENTRYPOINT ["/usr/bin/node"]
