#!/usr/bin/with-contenv bash
set -e

# install these packages using yarn, specified on runtime
# set yarn cache dir to fix https://stackoverflow.com/questions/59437833
# S6_YARN_PACKAGES=""; # list of packages passed at runtime, if required
if [ -n "${S6_YARN_PACKAGES}" ]; then
    YARN_CACHE_FOLDER=/root/.cache/yarn \
        s6-setuidgid root yarn global add ${S6_YARN_PACKAGES};
fi;

# S6_YARN_PROJECTDIR=""; # path to project passed at runtime, if required
# S6_YARN_LOCAL_PACKAGES=""; # list of packages passed at runtime, if required
if [ -n "${S6_YARN_PROJECTDIR}" ]; then
    if [ ! -d "${S6_YARN_PROJECTDIR}" ]; then # ensure exists and accessible by $PUID/$PGID
        mkdir -p ${S6_YARN_PROJECTDIR};
        chown ${S6_USER} ${S6_YARN_PROJECTDIR};
    fi;

    if [ -z "${S6_YARN_SKIP_INSTALL}" ] \
    && [ -f "${S6_YARN_PROJECTDIR}/package.json" ] \
    || [ -f "${S6_YARN_PROJECTDIR}/yarn.lock" ]; then
        cd ${S6_YARN_PROJECTDIR} \
        && YARN_CACHE_FOLDER=${S6_YARN_PROJECTDIR}/.cache/yarn \
        s6-setuidgid \
            $(ls -ldn . | awk 'NR==1 {print $3":"$4}') \
            yarn install;
    fi;
    if [ -n "${S6_YARN_LOCAL_PACKAGES}" ];
    then
        cd ${S6_YARN_PROJECTDIR} \
        && YARN_CACHE_FOLDER=${S6_YARN_PROJECTDIR}/.cache/yarn \
        s6-setuidgid \
            $(ls -ldn . | awk 'NR==1 {print $3":"$4}') \
            yarn add ${S6_YARN_LOCAL_PACKAGES};
    fi;
    # add project node_modules binaries dir to PATH
    # visible to with-contenv
    echo -en "${S6_YARN_PROJECTDIR}/node_modules/.bin:$PATH" > /run/s6/container_environment/PATH;
fi;
